[package]
name = "pssh-box-wasm"
version = "0.1.0"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
description = "Parsing and printing PSSH boxes, in WebAssembly."
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pssh-box = { path = "../pssh-box-rs", version = "*" }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.91" }
serde-wasm-bindgen = "0.6.3"
wasm-bindgen-futures = "0.4.41"
js-sys = "0.3.68"
console_error_panic_hook = "0.1.7"
html-escape = "0.2.13"
serde_json = "1.0.111"
thiserror = "1.0.57"

[dependencies.web-sys]
version = "0.3.68"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'Response',
  'Window',
]


[profile.release]
opt-level = 's'  # optimize for size
lto = true
codegen-units = 1
